smart_analytics_for_drupal.settings:
  type: config_object
  label: 'Smart Analytics for Drupal settings'
  mapping:
    ga4_property_id:
      type: string
      label: 'GA4 Property ID'
      description: 'The Google Analytics 4 measurement ID (e.g., G-XXXXXXX).'

    service_account_email:
      type: string
      label: 'Service Account Email'
      description: 'The client_email from the Google Cloud service account JSON.'

    key_reference:
      type: string
      label: 'Private Key'

    project_id:
      type: string
      label: 'Project ID'
      description: 'The Google Cloud project ID associated with the GA4 property.'

    token_uri:
      type: string
      label: 'Token URI'
      description: 'OAuth token URI used for service account authentication.'
      default_value: 'https://oauth2.googleapis.com/token'

    enabled_metrics:
      type: sequence
      label: 'Enabled Metrics'
      description: 'List of GA4 metrics to collect for content performance reports.'
      sequence:
        type: string
